# Generated by Django 4.2.3 on 2024-03-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analysis', '0002_log_report_threatintelligence_logevent_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_source_type', models.CharField(max_length=100)),
                ('required_fields', models.TextField()),
                ('parsing_patterns', models.TextField()),
            ],
        ),
    ]
